ב:
  - ב
  - בּ
ג:
  - ג
  - גּ
ד:
  - ד
  - דּ
כ:
  - כ
  - כּ
פ:
  - פ
  - פּ
ת:
  - ת
  - תּ
ש:
  - שׂ
  - שׁ
"":
  - ְ   # shva
  - ֳ   # hataf qamats
  - ֲ   # hataf patah
  - ֱ   # hataf segol
  - ִ   # hiriq
  - ֵ   # tsere
  - ֶ   # segol
  - ַ   # patah
  - ָ   # qamats
  - ֹ   # holam
  - ֻ   # qubuts
